config/routes.rb
Bulldog::Application.routes.draw do

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
      get '/edit_email' => 'registrations#edit_email', :via => :get, :as => :edit_email_user_registration
  end
  devise_for :users, path: "", controllers: {confirmations: 'confirmations',
                                              sessions: 'sessions',
                                              registrations: 'registrations'}

  # get '/remote_sign_in' => 'remote_content#remote_sign_in', as: :remote_sign_in

  resources :accounts do
    member do
      get 'cancel'
      get 'new_card'
      patch 'update_card'
    end
  end
  resources :bills, except: :show
  resources :customers, except: :show
  resources :invoices
  resources :reports, only: [:new, :create]
  get 'reports' => 'reports#new'
  resources :categories
  resources :vat_rates
  resources :settings, only: [:index, :show, :edit, :update]
  resources :suppliers, only: [:index, :edit, :update]
  resources :welcome, only: [:index]
  resources :plans, only: [:index]
  # post '/send_mail' => 'contacts#send_mail'
  resources :contacts, only: [:new, :create]
  # get "help/:action" => "help#:action"
  get 'help/intro' => 'help#intro'
  get 'help/account' => 'help#account'
  get 'help/bills' => 'help#bills'
  get 'help/categories' => 'help#categories'
  get 'help/customers' => 'help#customers'
  get 'help/invoices' => 'help#invoices'
  get 'help/logo' => 'help#logo'
  get 'help/print_settings' => 'help#print_settings'
  get 'help/reports' => 'help#reports'
  get 'help/setup' => 'help#setup'
  get 'help/subscription' => 'help#subscription'
  get 'help/suppliers' => 'help#suppliers'
  get 'help/vat' => 'help#vat'
  get 'help/video' => 'help#video'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  # include Visible
  belongs_to :account
  belongs_to :customer
  belongs_to :header
  has_many   :bills

  #scope :current, -> { where(account_id: current_account.id) }

  validates_uniqueness_of :number, scope: :account_id
  validates :customer_id, :date, presence: true

  validate :customer_has_uninvoiced_bills?, on: :create
  validates :from_date, :to_date, date: true, allow_blank: true
  #validate :from_date_after_to_date

  attr_accessor :new_header, :from_date, :to_date
  before_save :create_header

  def self.next_number(account)
    self.where(account_id: account.id).last ? self.where(account_id: account.id).last.number.next : '1'
  end

  def customer_name
    customer.name
  end

  def header_name
    header ? header.name : ""
  end

  def setting
    account.setting
  end
  def include_bank_details?
    include_bank
  end

  def include_vat?
    include_vat
  end

  def self.import(file, account)
    # used to import via the console
    # bills must be loaded first
    # the account must be empty before this
    CSV.foreach(file, headers: true) do |row|
      invoice = new
      imported = row.to_hash
      invoice.account_id = account.id
      invoice.customer_id = account.customers.find_by_name(imported['customer']).id
      invoice.date = imported['date']
      invoice.number = imported['id']
      invoice.total = imported['total']
      invoice.comment = imported['comment']

      invoice.save
    end
  end

  private

  def customer_has_uninvoiced_bills?
    unless self.customer.blank?
      if self.customer.has_uninvoiced_bills?
        return true
      else
        errors.add(:customer_id, "This customer has no bills")
        return false
      end
    else
      # errors.add(:customer_id, "can't be blank")
      return false
    end
  end

  def self.customer_filter(customer)
    logger.debug "*** customer passed in to filter: #{customer}"
    if customer.present? && customer[:customer_id] != ""
      logger.debug "*** now in if side of customer filter"
      where(customer_id: customer[:customer_id])
    else
      logger.debug "*** now in else side of customer filter"
      all
    end
  end

  def self.filter_from(date)
    if date.present? && date_valid?(date)
      where('date >= :q', q: "#{date}")
    else
      all
    end
  end

  def self.filter_to(date)
    if date.present? && date_valid?(date)
      where('date <= :q', q: "#{date}")
    else
      all
    end
  end

  def self.search(search)
    if search.present?
      # where('customer_id in (select id from customers where name ilike :q)', q: "%#{search}%")
      where('comment ilike :q', q: "%#{search}%")

    else
      all
    end
  end

  def create_header
    self.header = Header.create(name: new_header, account_id: self.account_id) if new_header.present?
  end

  def self.date_valid?(date)
    true if (date.is_a?(Date) || date =~ /\A\d{4}-\d{2}-\d{2}\z/ ) &&
      begin
        date.to_date.is_a?(Date)
      rescue ArgumentError
        false
      end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :authenticate_user!
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  helper_method :sort_column, :sort_direction

  def index
    @invoices = policy_scope(Invoice).includes(:customer).
                                 # customer_filter(params["inv_customer_id"]).
                                 customer_filter(params[:invoice]).
                                 search(params[:search]).
                                 filter_from(params[:from_date]).
                                 filter_to(params[:to_date]).
                                 page(params[:page]).
                                 order(sort_column + " " + sort_direction)
    authorize @invoices
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @invoice = current_account.invoice(params[:id])
    authorize @invoice
    @customers = []
    @customers << @invoice.customer
    @bills = @invoice.bills.includes(:category, :supplier, :vat_rate).order(date: :asc)

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        pdf = InvoicePdf.new(@invoice, @bills, view_context)
        send_data pdf.render, filename: "invoice_#{@invoice.number}",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def new
    @invoice = current_account.invoices.build
    authorize @invoice
    @invoice.date = Date.today
    @customers = current_account.customers
  end

  def edit
    # @invoice = current_account.invoice(params[:id])
    @invoice = policy_scope(Invoice).find(params[:id])
    authorize @invoice
    @customers = []
    @customers << @invoice.customer
    @bills = @invoice.bills.includes(:category, :supplier, :vat_rate)
  end

  def update
    collect_new_entries
    @invoice = policy_scope(Invoice).find(params[:id])
    # @invoice = current_account.invoice(params[:id])
    authorize @invoice
    @customers = []
    @customers << @invoice.customer
    if params[:bill_ids]
      Bill.where('id IN (?)', params[:bill_ids]).update_all(invoice_id: nil)
    end
    total = @invoice.bills.sum(:amount)
    if @invoice.update(invoice_params.merge(total: total))
      flash[:success] = "Document successfully updated"
      redirect_to @invoice
    else
      render 'edit'
    end
  end

  def create
    collect_new_entries
    @invoice = Invoice.new(invoice_params)
    authorize @invoice
    @invoice.number = Invoice.next_number(current_account)
    @bills =  current_account.bills.uninvoiced.where(customer_id: @invoice.customer_id).order(date: :desc)
    @invoice.total = @bills.sum(:amount)
    @customers = current_account.customers # in case of no save
    @invoice.include_vat = current_account.setting.include_vat  # set default
    @invoice.include_bank = current_account.setting.include_bank  # set default

    if @invoice.save
      @bills.each do |bill|
            bill.update_attribute(:invoice_id, @invoice.id)
            # bill.save
          end
      session[:new_invoice] = true
      redirect_to edit_invoice_path(@invoice)
    else
      render :new
    end
  end

  def destroy
    @invoice = current_account.invoice(params[:id])
    authorize @invoice
    @invoice.bills.each do |bill|
                   bill.invoice_id = nil
                   bill.save
                 end
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
    end
  end

  private

  def valid_string?(str)
    # not blank, not nil and not a string representation of an integer
    # all params are strings so valid ids need converting
    str.present? && str.to_i == 0
  end

  def collect_new_entries
    # params[:invoice][:new_header] = params[:invoice][:header_id] if params[:invoice][:header_id].to_i == 0
    if valid_string?(params[:invoice][:header_id])
      new_id = Header.create(name: params[:invoice][:header_id], account_id: current_account.id).id
      if new_id
        params[:invoice][:header_id] = new_id.to_s
      else
        params[:invoice][:header_id] = nil
      end
    end
  end

  def invoice_params
    params.require(:invoice).permit(*policy(@invoice || Invoice).permitted_attributes)
  end

  def sort_column
    %w[id number customers.name date total comment].include?(params[:sort]) ? params[:sort] : "id"
  end

   def sort_direction
     %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
   end

end

app/helpers/invoices_helper.rb
module InvoicesHelper

  def total_vat(invoice)
    invoice.bills.sum(:vat)
  end

  def vat_by_rate(invoice, rate)
    invoice.bills.vat(rate).sum(:vat)
  end

  def vat_rates(bills)
    rates = bills.map {|bill| bill.vat_rate}.uniq.compact
  end

  def logo_file(invoice)
    if invoice.account.setting.logo_file_name.present?
      invoice.account.setting.logo.url(:medium)
    else
      nil
    end
  end

  def current_plan_name(account)
    if account.plan_id == 0
      "no current subscription"
    else
      account.plan.name + " at " +
      number_to_currency(@account.plan.amount/100) + " per " +
      @account.plan.interval
    end
  end

  def next_invoice_date(account)
    if account.next_invoice.present?
      account.next_invoice.strftime("%d/%m/%Y")
    else
      "NA"
    end
  end

  def time_to_next_invoice(account)
    if account.next_invoice.present?
      if account.next_invoice > Time.now
        " - still #{distance_of_time_in_words(Time.now, account.next_invoice)} to go"
      else
        " - no unused subscription"
      end
    else
      ""
    end
  end

  def current_card(account)
    if account.card_last4.present?
      account.card_last4
    else
      "NA"
    end
  end

  def logo_thumb(setting)
    if setting.logo_file_name
      image_tag setting.logo.url(:thumb)
    else
      "No logo uploaded"
    end
  end
end

app/views/invoices/_bill_fields.html.erb
<tr>
  <% if params[:action] == 'edit' %>
    <td class="remove-col"><%= check_box_tag "bill_ids[]", f.id %></td>
  <% end %>
  <td class="first-col date-col"><%= f.date %></td>
  <td class="supplier-col"><%= f.supplier_name %></td>
  <td class="category-col"><%= f.category_name %></td>
  <td class="description-col"><%= f.description %></td>
  <td class="align-right amount-col"><%= number_to_currency(f.amount) %></td>
  <% if current_account.vat_allowed? %>
    <td class="vat-rate-col"><%= f.vat_rate_name %></td>
    <td class="align-right amount-col"><%= number_to_currency(f.vat) %></td>
  <% end %>
</tr>

app/views/invoices/_edit_header.html.erb
<%= f.hidden_field :account_id %>

<% if params[:action] == 'new' %>
  <%= form_group_for f, :customer_id, label: false do%>
    <div class="customer-select invoice-edit">
      <%= f.collection_select :customer_id, @customers, :id, :name%>
    </div>
  <% end %>

<% else %>
  <table class="invoice-edit">
    <tr>
      <th class="th-invoice">Customer:</th>
      <td class="td-invoice"><%= @invoice.customer_name %></td>
    </tr>
  </table>
<% end %>

<%= form_group_for f, :date, label: false do %>
  <div class="input-group invoice-edit">
    <%= f.label :name, "Date:" %>
    <%= f.text_field :date, class: "date_picker invoice-date-picker" %>
  </div>
<% end %>

<%= form_group_for f, :header_id, label: false do %>
  <div class="input-group invoice-edit invoice-header">
  <!-- <div class="input-group invoice-edit"> -->
    <%= f.label :header, "Header:" %>
    <%= f.collection_select(:header_id, current_account.headers.order(:name), :id, :name, prompt: true) %>
  </div>
<% end %>

<%= form_group_for f, :comment, label: false do %>
  <div class="input-group invoice-edit">
    <%= f.label :comment, "Comment:" %>
    <%= f.text_area :comment, placeholder: "Document comment - appears on PDF", class: 'form-control' %>
  </div>
<% end %>

<% if current_account.vat_allowed? %>
  <%= form_group_for f, :include_vat, label: false do %>
    <div class="input-group invoice-edit">
      <%= f.label :include_vat, :class => "check"%>
      <%= f.check_box :include_vat %>
    </div>
  <% end %>
<% end %>

<%= form_group_for f, :include_bank, label: false do %>
  <div class="input-group invoice-edit">
    <%= f.label :include_bank, :class => "check" %>
    <%= f.check_box :include_bank %>
  </div>
<% end %>

<%= f.submit 'Save Changes', class: 'create-btn std-btn', data: {toggle: "tooltip"}, title: "Save changes"  %>

<% if session[:new_invoice] == true then %>
  <% session[:new_invoice] = nil %>
<% else %>
  <%= link_to 'Cancel', invoices_path, class: 'action-btn std-btn', data: {toggle: "tooltip"}, title: "Cancel and return to document list"  %>
<% end %>

<%= link_to 'Delete', @invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'warn-btn std-btn', title: "Delete document and return bills to pool"  %>

app/views/invoices/_filter_form.html.erb
<%= form_tag invoices_path, method: 'get', id: "invoices_search" do %>
  <div class="form-group invoice">
    <%= label_tag :from_date %>
    <%= text_field_tag :from_date, params[:from_date], class: "date_picker", placeholder: "yyyy-mm-dd" %>
  </div>
  <div class="form-group invoice">
    <%= label_tag :to_date %>
    <%= text_field_tag :to_date, params[:to_date], class: "date_picker", placeholder: "yyyy-mm-dd" %>
  </div>
  <div class="form-group" id="inv_customer_id">
    <%= collection_select(:invoice, :customer_id, current_account.customers.order(:name), :id, :name, prompt: :true) %>
  </div>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: "search-query form-control", placeholder: ' by text within comment' %>
  </div>
  <div>
    <%= submit_tag "Filter", name: nil, class: "create-btn std-btn", data: {toggle: "tooltip"}, title: "Submits filter choices to refresh data" %>
    <a class="action-btn std-btn" data-toggle="modal" data-dismiss="modal">Cancel</a>
  </div>
<% end %><!-- end of form -->

app/views/invoices/_filter_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="invoice_filter_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="modal_title">Filter Documents</h4>
      </div><!-- /.modal-header -->
      <div class="modal-body" id="invoice_filter_form">
        <%= render 'filter_form' %>
      </div><!-- /.modal-body -->
      <div class="modal-footer"> </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/invoices/_form.html.erb
  <div class="table-responsive">
    <table class="table table-condensed" id="bill_table">
      <thead>
        <tr>
          <% if params[:action] == 'edit' %>
            <th>Remove?</th>
          <% end %>
          <th class="first-col date-col">Date</th>
          <th class="supplier-col">Supplier</th>
          <th class="category-col">Category</th>
          <th class="description-col-lg">Description</th>
          <th class="amount-col align-right">Amount</th>
          <% if current_account.vat_allowed? %>
            <th class="vat-rate-col">VAT rate</th>
            <th class="amount-col align-right">VAT</th>
          <% end %>
        </tr>
      </thead>

      <tbody id="bill_table_body">
        <% @bills.each do |bill| %>
          <%= render 'bill_fields', f: bill %>
        <% end %>
      </tbody>

      <tfoot class="no-line">
        <tr class="underline">
          <% if params[:action] == 'edit' %>
            <td></td>
          <% end %>
          <td></td>
          <td></td>
          <td></td>
          <td class="title-td align-right">Total </td>
          <td class="align-right"><%= number_to_currency(@invoice.total) %></td>
          <% if current_account.vat_allowed? %>
            <td></td>
            <td class="align-right"><%= number_to_currency(total_vat(@invoice)) %></td>
          <% end %>
        </tr>

        <% if current_account.vat_allowed? %>
          <% vat_rates(@bills).each_with_index do |rate, index| %>
            <tr>
              <% if params[:action] == 'edit' %>
                <td></td>
              <% end %>
              <td></td>
              <td></td>
              <td></td>
              <td colspan="2" class="title-td align-right"><%= "VAT Summary" if index == 0 %></td>
              <td class=""><%= rate.name if rate %></td>
              <td class="align-right"><%= number_to_currency(vat_by_rate(@invoice, rate)) if rate %></td>
             </tr>
           <% end %>
         <% end %>
      </tfoot>
    </table>
  </div>

app/views/invoices/_invoice.html.erb
<tr title="click to show details" class="pointer rowlink" data-rowlink="<%= invoice_path(invoice)%>">
  <td class="first-col number-col"><%= invoice.number %></td>
  <td class="date-col"><%= invoice.date %></td>
  <td class="customer-col"><%= invoice.customer_name %></td>
  <td class="comment-col"><%= truncate(invoice.comment, length: 60, separator: ' ') %></td>
 <td class="align-right amount-col"><%= number_to_currency(invoice.total) %></td>
</tr>

app/views/invoices/_new_form.html.erb
<%= form_for @invoice do |f| %>
  <%= f.hidden_field :account_id %>
  <%= form_group_for f, :date, label: false do %>
    <%= f.text_field :date, class: "date_picker invoice-date-picker" %>
  <% end %>
  <%= form_group_for f, :customer_id, label: false do %>
    <%= f.collection_select(:customer_id, current_account.customers.order(:name), :id, :name, prompt: true) %>
  <% end %>

  <%= form_group_for f, :header_id, label: false do %>
    <%= f.collection_select(:header_id, current_account.headers.order(:name), :id, :name, prompt: true) %>
  <% end %>

  <%= form_group_for f, :comment, label: false do %>
    <%= f.text_area :comment, placeholder: "Comment - will appear on printed document", rows: "5" %>
  <% end %>

  <%= f.submit 'Create Document', class: 'create-btn std-btn', data: {toggle: "tooltip"}, title: "Create a new document"  %>
  <%= link_to 'Cancel', invoices_path, class: 'action-btn std-btn', data: {toggle: "tooltip"}, title: "Cancel and return to list of documents"  %>

<% end %>

app/views/invoices/_show_header.html.erb
<div class="panel panel-default col-md-6 col-sm-8 invoice_header">
    <div class="panel-body">
        <table class="invoice-show">
          <tr>
            <th class="th-invoice">Customer:</th>
            <td class="td-invoice"><%= @invoice.customer_name %></td>
          </tr>
          <tr>
            <th class="th-invoice">Document Date:</th>
            <td class="td-invoice"><%= @invoice.date %></td>
          </tr>
          <tr>
            <th class="th-invoice">Header:</th>
            <td class="td-invoice"><strong><%= @invoice.header_name %></strong></td>
          </tr>
          <tr>
            <th class="th-invoice th-comment">Comment:</th>
            <!-- <td class="td-invoice"><%#= simple_format(@invoice.comment) %> -->
            <td class="td-invoice"><%= simple_format truncate(@invoice.comment, length: 190, separator: ' ') %>
            </td>
          </tr>
          <% if current_account.vat_allowed? %>
            <tr>
              <th class="th-invoice">Print VAT details?</th>
              <!-- <td class="td-invoice"><%= checkbox_image(@invoice.include_vat).html_safe %></td> -->
              <td class="td-invoice"><%= @invoice.include_vat ? "Yes" : "No" %></td>
            </tr>
          <% end %>
          <tr>
            <th class="th-invoice">Print Bank details?</th>
            <!-- <td class="td-invoice"><%= checkbox_image(@invoice.include_bank).html_safe %></td> -->
            <td class="td-invoice"><%= @invoice.include_bank ? "Yes" : "No" %></td>
          </tr>
        </table>

          <%=  link_to 'Edit', edit_invoice_path(@invoice), class: 'create-btn std-btn', data: {toggle: "tooltip"}, title: "Edit selected document"  %>

          <%= link_to "Back", invoices_path, class: 'action-btn std-btn', data: {toggle: "tooltip"}, title: "Return to document list"  %>

          <%= link_to "Print Preview", invoice_path(@invoice, format: "pdf"), class: 'create-btn std-btn', target: "_blank", data: {toggle: "tooltip"}, title: "Download PDF of document for print or email"  %>
      </div>
    </div>

app/views/invoices/_table.html.erb
<div class="table-responsive">
  <table class="table table-hover table-condensed" id="invoice_table">
    <thead>

      <tr>
        <th class="first-col number-col"><%= sortable "id", "No." %> <%= arrow "id" %></th>
        <th class="date-col"><%= sortable "date", "Date" %> <%= arrow "date" %></th>
        <th class="customer-col"><%= sortable "customers.name", "Customer" %> <%= arrow "customers.name" %></th>
        <th class="comment-col"><%= sortable "comment", "Comment" %> <%= arrow "comment" %></th>
        <th class="amount-col"><%= sortable "total", "Amount" %> <%= arrow "total" %></th>
      </tr>
    </thead>
    <tbody id="invoice_index_table">
      <%# @invoices.each do |invoice| %>
      <%= render @invoices %>
      <%# end %>
    </tbody>
  </table>
</div><!--end table responsive -->

app/views/invoices/edit.html.erb
<% content_for :title do %>BulldogClip | Edit Document<% end %>
<% content_for :description do %>Edit document<% end %>
<div class="container">
    <h1>Document <%= @invoice.number %></h1>

     <a href="#" id="pop" class="info-btn pop"
     data-title="Edit Document"
     data-content="
     <ul class='info-ul'>
     <li>Select any bills that you want to remove from the document. Once you are happy with all your changes use the 'Save Changes' button to confirm.</li>
     <li>Use 'Delete' to remove the document and return all the bills to the the pool.
     <li>*Note if you have created a document for the wrong customer, delete this document, then edit the bills to be associated with the correct customer before creating a new document.</li>
     <li>The 'Print Preview' button will generate a PDF of the fully formatted document in a new window for you to download or print.</li>
     <li>To return to the document index use 'Cancel'</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

  <%= form_for @invoice do |f| %>
    <div class="panel panel-default col-md-6 col-sm-8" style="float:none">
      <div class="panel-body">
        <%= render 'edit_header', f: f %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', f: f %>
      </div>
    </div>
  <% end %><!-- end of form_for -->
</div>

app/views/invoices/index.html.erb
<% content_for :title do %>BulldogClip | Documents<% end %>
<% content_for :description do %>BulldogClip documents index<% end %>

<div class="container">
  <h1>Documents</h1>
     <a href="#" id="pop" class="info-btn pop"
     data-title="Documents Index"
     data-content="
     <ul class='info-ul'>
     <li>This is a list of all your documents.</li>
     <li>You must have bills in the system before you can create a document.</li>
     <li>Select a row to show or edit document details.</li>
     <li>Use 'New Document' to create a document.</li>
     <li>Use 'Filter' to find a document by date, customer or comment.</li>
     <li>Use 'Clear' to reset the data removing any filters</li>
     <li>Click on column headings to sort the data table.</li>

     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

  <%#= render 'filter_form' %>

  <div class="panel panel-default">
    <div class="panel-body">
    <div>
          <a class="create-btn std-btn" href='#' data-toggle="modal" data-target="#invoice_filter_modal" title="Select criteria to filter the list by">Filter</a>
          <%#= submit_tag "Filter", name: nil, class: "create-btn std-btn", data: {toggle: "tooltip"}, title: "Submits filter choices to refresh data" %>
          <%= link_to "Clear", invoices_path, class: "action-btn std-btn", data: {toggle: "tooltip"}, title: "Clear current filters" %>
          <%= link_to "New Document", new_invoice_path, class: "create-btn std-btn", data: {toggle: "tooltip"}, title: "Create a new document." %>
        </div>

    <!-- Displays first bill video if no bills or bill table -->
      <% if current_account.invoices.empty? %>
        <%= render 'video' %>
      <% else %>
        <%= render 'table' %>
      <% end %>

      <div id="paginator"><%= paginate @invoices, remote: true %></div>
    </div><!--end panel body -->
  </div><!--end panel-->
</div><!-- end container -->
<%= render 'filter_modal' %>

app/views/invoices/index.js.erb
$('#flashes').remove();
$('main').prepend("<%= escape_javascript raw(flash_normal) %>");
$('tbody#invoice_index_table').html('<%= escape_javascript render @invoices %>');
$('#paginator').html('<%= escape_javascript(paginate(@invoices, :remote => true).to_s) %>');
$('#filter_modal').modal('hide');

app/views/invoices/new.html.erb
<% content_for :title do %>BulldogClip | New Document<% end %>
<% content_for :description do %>Create new document<% end %>
<div class="container">
  <div class="panel panel-default col-md-4 col-md-offset-4">
    <div class="panel-body">
    <h1>New Document</h1>

     <a href="#" id="pop" class="info-btn pop"
     data-title="Create New Document"
     data-content="
     <ul class='info-ul'>
     <li>Enter the date you want to appear on the document.</li>
     <li>Select the customer and add any comments.</li>
     <li>When you click on 'Create Document' the system will fetch all undocumented bills for the chosen customer and display them.</li>
     <li>You will have the opportunity to remove any unwanted bills.</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

      <%= render 'new_form' %>
    </div>
  </div>
</div>

app/views/invoices/show.html.erb
<% content_for :title do %>BulldogClip | Show Document<% end %>
<% content_for :description do %>Show document<% end %>
<div class="container">
    <h1>Document <%= @invoice.number %></h1>
     <a href="#" id="pop" class="info-btn pop"
     data-title="Review A Document"
     data-content="
     <ul class='info-ul'>
     <li>Use the 'Edit' button to change the comment or remove bills from this document.</li>
     <li>'Print Preview' opens a fully formatted PDF version in a new window for you to download or print.</li>
     <li>Select 'Back' to return to the list of documents.</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

     <%= render 'show_header' %>
  <div class="panel panel-default">
    <div class="panel-body">
        <%= render 'form' %>
    </div>
  </div>
</div>