config/routes.rb
Bulldog::Application.routes.draw do

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
      get '/edit_email' => 'registrations#edit_email', :via => :get, :as => :edit_email_user_registration
  end
  devise_for :users, path: "", controllers: {confirmations: 'confirmations',
                                              sessions: 'sessions',
                                              registrations: 'registrations'}

  # get '/remote_sign_in' => 'remote_content#remote_sign_in', as: :remote_sign_in

  resources :accounts do
    member do
      get 'cancel'
      get 'new_card'
      patch 'update_card'
    end
  end
  resources :bills, except: :show
  resources :customers, except: :show
  resources :invoices
  resources :reports, only: [:new, :create]
  get 'reports' => 'reports#new'
  resources :categories
  resources :vat_rates
  resources :settings, only: [:index, :show, :edit, :update]
  resources :suppliers, only: [:index, :edit, :update]
  resources :welcome, only: [:index]
  resources :plans, only: [:index]
  # post '/send_mail' => 'contacts#send_mail'
  resources :contacts, only: [:new, :create]
  # get "help/:action" => "help#:action"
  get 'help/intro' => 'help#intro'
  get 'help/account' => 'help#account'
  get 'help/bills' => 'help#bills'
  get 'help/categories' => 'help#categories'
  get 'help/customers' => 'help#customers'
  get 'help/invoices' => 'help#invoices'
  get 'help/logo' => 'help#logo'
  get 'help/print_settings' => 'help#print_settings'
  get 'help/reports' => 'help#reports'
  get 'help/setup' => 'help#setup'
  get 'help/subscription' => 'help#subscription'
  get 'help/suppliers' => 'help#suppliers'
  get 'help/vat' => 'help#vat'
  get 'help/video' => 'help#video'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  before_action :route_according_to_account_state

  def index
  end

  private

  def route_according_to_account_state

    case current_account.state
    when "paid"
      route_paid
    when "trialing"
      check_trial_end_date
    when "paying"
      route_paying
    when "expired"
      route_expired
    when "charge_failed"
      route_charge_failed
    when "closed"
      route_closed
    when "deleted"
      route_deleted
    else
      route_contact # something went wrong
    end
  end

  def check_trial_end_date
    if current_account.trial_end < Time.now
      current_account.expire!
      route_expired
    else
      route_paid
    end
  end

  def route_paid
    # continue to index
  end

  def route_paying
    # allow 'paying' to have access to avoid 1 hour delay and assuming charge will succeed
    # added 'paying' to definition of 'active?' in account model
    # flash[:alert] = "You card payment is still being processed, please try again soon"
    # redirect_to page_path('waiting_payment')
  end

  def route_expired
    flash[:error] = "Your free_trial has ended, please supply payment card details to continue"
    redirect_to new_card_account_path(current_account)
  end

  def route_charge_failed
    flash[:error] = "A recent attempt to charge your card has failed. Please confirm your card details to continue"
    redirect_to new_card_account_path(current_account)
  end

  def route_closed
    flash[:error] = "Your account is closed, you can rejoin by subscribing here using your saved card"
    redirect_to edit_account_path(current_account)
  end

  def route_deleted
    flash[:error] = "Your account has been deleted. To re-activate it please contact us"
    sign_out current_user
    redirect_to new_contact_path
  end

  def route_contact
    flash[:error] = "Something may have gone wrong here. Please let us know what happened."
    sign_out current_user
    redirect_to new_contact_path
  end
end

app/views/welcome/_first_sign_in.html.erb
Modal -->
  <div class="modal fade" id="first_sign_in_modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content first_sign_in">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
          <h4 class="modal-title" id="modal_title">Welcome to BulldogClip</h4>
        </div>
        <div class="modal-body" id="first_sign_in">
          <!-- <p>Thank you for subscribing.</p> -->
          <!-- <br> -->
          <p>As this is your first login you may like to read the getting started guide. This will open in a new tab or window so that you can keep it open whilst using BulldogClip.</p>
          <br>
          <p>You can also access this at any time from the help button on the right of the screen. To continue using BulldogClip, come back to this window and click on ’Start using BulldogClip’.</p>
          <br>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="action-btn std-btn" data-dismiss="modal">Continue</button> -->
          <%= link_to 'Read Getting Started', '/help/intro', target: ("_blank"), class: "action-btn lg-btn pull-left" %>
          <%= link_to 'Start using BulldogClip', '#', class: "create-btn lg-btn", data: { dismiss: 'modal'} %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal

app/views/welcome/index.html.erb
<% content_for :title do %>BulldogClip | Welcome<% end %>
<% content_for :description do %>A place to keep receipts<% end %>

<%= render 'first_sign_in' if first_sign_in? %>

<div class= "container ">
  <div class="row welcome">
    <div class="col-xs-10 col-xs-offset-1">
    <div class="panel panel-default welcome">
      <div class="panel-body">
      <a href="/bills" class="clickable-block">
      <img src=<%= asset_path('bills_icon.png') %> alt="bills icon image" class="image-responsive welcome">
        <p>Bills</p>
      </a>
     </div>
    </div>
    <div class="panel panel-default welcome">
      <div class="panel-body">
      <a href="/invoices" class="clickable-block">
          <img src=<%= asset_path('invoices_icon.png') %> alt="documents icon image" class="image-responsive welcome">
          <p>Documents</p>
      </a>
      </div>
    </div>
    <div class="panel panel-default welcome">
      <div class="panel-body">
      <a href="/reports" class="clickable-block">
        <img src=<%= asset_path('analysis_icon.png') %> alt="analysis icon image" class="image-responsive welcome">
        <p>Analysis</p>
      </a>
      </div>
    </div>
    <div class="panel panel-default welcome flipable">
      <div class="panel-body front card">
      <img src=<%= asset_path('tools_icon.png') %> alt="tools icon image" class="image-responsive welcome">
      <a href="#" class="subnav-btn">Tools</a>
      </div>
      <div class="panel-body back card">
        <ul class="tools-flip-menu">
          <li><%= link_to 'Customers', customers_path, class: 'menu-item' %></li>
          <hr>
          <li><%= link_to 'Categories', categories_path, class: 'menu-item' %></li>
          <hr>
          <li><%= link_to 'Suppliers', suppliers_path, class: 'menu-item' %></li>
          <hr>
          <% if current_account.vat_allowed? %>
            <li><%= link_to 'VAT Rates', vat_rates_path, class: 'menu-item' %></li>
            <hr>
          <% end %>
          <li><%= link_to 'Document Setup', settings_path, class: 'menu-item' %></li>
          <hr>
        </ul>
      </div>
    </div>

    <div class="panel panel-default welcome flipable">
      <div class="panel-body front card">
          <img src=<%= asset_path('account_icon.png') %> alt="account icon image" class="image-responsive welcome">
      <a href="#" class="subnav-btn">Account</a>
      </div>
      <div class="panel-body back card">
        <ul class="tools-flip-menu">
          <li><%= link_to 'Change Password', edit_user_registration_path, class: "menu-item" %></li>
          <hr>
          <li><%= link_to 'Change Email Address', edit_email_user_registration_path, class: "menu-item" %></li>
          <hr>
          <li><%= link_to 'Manage Subscription', account_path(current_account), class: "menu-item" %></li>
          <hr>
        </ul>
      </div>
    </div>
    <div class="panel panel-default welcome">
      <div class="panel-body">
        <a href="/news" class="clickable-block">
          <img src=<%= asset_path('news_icon.png') %> alt="news icon image" class="image-responsive welcome">
          <p>News</p>
        </a>
      </div>
    </div>
  </div>
  </div>
</div> <!-- end container -->