config/routes.rb
Bulldog::Application.routes.draw do

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
      get '/edit_email' => 'registrations#edit_email', :via => :get, :as => :edit_email_user_registration
  end
  devise_for :users, path: "", controllers: {confirmations: 'confirmations',
                                              sessions: 'sessions',
                                              registrations: 'registrations'}

  # get '/remote_sign_in' => 'remote_content#remote_sign_in', as: :remote_sign_in

  resources :accounts do
    member do
      get 'cancel'
      get 'new_card'
      patch 'update_card'
    end
  end
  resources :bills, except: :show
  resources :customers, except: :show
  resources :invoices
  resources :reports, only: [:new, :create]
  get 'reports' => 'reports#new'
  resources :categories
  resources :vat_rates
  resources :settings, only: [:index, :show, :edit, :update]
  resources :suppliers, only: [:index, :edit, :update]
  resources :welcome, only: [:index]
  resources :plans, only: [:index]
  # post '/send_mail' => 'contacts#send_mail'
  resources :contacts, only: [:new, :create]
  # get "help/:action" => "help#:action"
  get 'help/intro' => 'help#intro'
  get 'help/account' => 'help#account'
  get 'help/bills' => 'help#bills'
  get 'help/categories' => 'help#categories'
  get 'help/customers' => 'help#customers'
  get 'help/invoices' => 'help#invoices'
  get 'help/logo' => 'help#logo'
  get 'help/print_settings' => 'help#print_settings'
  get 'help/reports' => 'help#reports'
  get 'help/setup' => 'help#setup'
  get 'help/subscription' => 'help#subscription'
  get 'help/suppliers' => 'help#suppliers'
  get 'help/vat' => 'help#vat'
  get 'help/video' => 'help#video'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  # include Visible

  belongs_to :account
  belongs_to :customer
  belongs_to :supplier
  belongs_to :category
  belongs_to :vat_rate
  belongs_to :invoice

  validates :date, date: true
  # validates :account_id, :date, :customer, :supplier, :category, :amount, presence: true
  validates :account_id, :date, :customer_id, :supplier_id, :category_id, :amount, presence: true
  # validates_associated :supplier, :category, :customer
  validates :amount, numericality: true

  # attr_accessor :new_category, :new_supplier, :new_customer
  # before_save :create_category, :create_customer #, :create_supplier,
  before_destroy :check_for_invoice

  scope :uninvoiced, -> {where(invoice_id: nil)}
  scope :this_year, -> {where(date: Time.now.all_year)}
  scope :last_year, -> {where(date: Time.now.prev_year.all_year)}
  scope :vat,       -> (rate){where(vat_rate_id: rate.id)}

  def customer_name
    customer ? customer.name : "Missing - please edit"
  end
  def supplier_name
    supplier ? supplier.name : "Missing - please edit"
  end
  def category_name
    category ? category.name : "Missing - please edit"
  end
  def excl_vat
    vat ? amount - vat : amount
  end
  def vat_rate_name
    vat_rate_id ? vat_rate.name : ""
  end
  def vat_rate_value
    vat_rate_id ? vat_rate.rate.to_s : ""
  end
  def invoice_number
    invoice_id ? invoice.number : ""
  end

  def self.to_csv(options = {})
    return unless first # at least one bill
    if first.account.business?
      CSV.generate(options) do |csv|
        csv << %w{Date Customer Supplier Category Description Amount VAT_rate VAT Invoice}
        all.each do |bill|
          row = [bill.date, bill.customer_name, bill.supplier_name, bill.category_name,
                bill.description, bill.amount, bill.vat_rate_name, bill.vat, bill.invoice_number]
          csv << row
        end
      end
    else
    CSV.generate(options) do |csv|
      csv << %w{Date Customer Supplier Category Description Amount Invoice}
      all.each do |bill|
        row = [bill.date, bill.customer_name, bill.supplier_name, bill.category_name,
              bill.description, bill.amount, bill.invoice_number]
        csv << row
      end
    end
    end
  end

  def self.import(file, account)
    # used to manually (via console) import from old bulldog
    # account should be empty of bills
    CSV.foreach(file, headers: true) do |row|
      bill = new
      imported = row.to_hash
      bill.date = imported['transaction_date']
      bill.customer = account.customers.find_or_create_by(name: imported['customer'])
      bill.supplier = account.suppliers.find_or_create_by(name: imported['supplier'])
      bill.category = account.categories.find_or_create_by(name: imported['category'])
      bill.description = imported['description']
      bill.amount = imported['amount']
      bill.invoice_id = imported['invoice_id']
      bill.account_id = account.id
      bill.save!
    end
  end

  def self.update_invoice_ids(invoice)
    # used to update bills via console after invoices are loaded
    number = invoice.number.to_i + 5000
    bills = Bill.where(invoice_id: number, account_id: invoice.account_id)
    bills.each do |bill|
      bill.update_attribute(:invoice_id, invoice.id)
    end
  end

  MNTHS = %w[Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec]

  def self.last_year_by_monthly_sum
    q = last_year.monthly_sum
    result = {}
    12.times{|i| result[MNTHS[i]] = q[i+1] || 0.0}
    result
  end

  def self.this_year_by_monthly_sum
    q = this_year.monthly_sum
    result = {}
    12.times{|i| result[MNTHS[i]] = q[i+1] || 0.0}
    result
  end

  def self.this_year_by_monthly_count
    q = this_year.monthly_count
    result = {}
    12.times{|i| result[MNTHS[i]] = q[i+1] || 0.0}
    # result
    {name: this_year_label, data: result}
  end

  def self.last_year_by_monthly_count
    q = last_year.monthly_count
    result = {}
    12.times{|i| result[MNTHS[i]] = q[i+1] || 0.0}
    # result
    {name: last_year_label, data: result}
  end

  def self.last_year_label
    Date.today.prev_year.year.to_s
  end

  def self.this_year_label
    Date.today.year.to_s
  end

  # If timestamp is required for Y-axis then you can use groupdate functions e.g. group_by_month
  # This monthly_sum method returns integers 1 to 12 to represent months so that multiple years can be laid
  # over each other in chartkick charts. Note that this is only available for bar or column charts.
  def self.monthly_sum
    order(Arel.sql("cast(EXTRACT(month FROM date) as integer)")).
    group("cast(EXTRACT(month FROM date) as integer)").
    sum(:amount)
  end


  def self.monthly_count
    order(Arel.sql("cast(EXTRACT(month FROM date) as integer)")).
    group("cast(EXTRACT(month FROM date) as integer)").
    count
  end


  private

  # def create_customer
  #   self.customer = Customer.create(name: new_customer, account_id: self.account_id) if new_customer.present?
  # end

  # def create_category
  #   self.category = Category.create(name: new_category, account_id: self.account_id) if new_category.present?
  # end

  # def create_supplier
  #   self.supplier = Supplier.create(name: new_supplier, account_id: self.account_id) if new_supplier.present?
  # end

  def check_for_invoice
    unless self.invoice_id.blank?
      errors.add(:amount, "This bill is invoiced and cannot be deleted")
      throw :abort
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  # after_action :verify_policy_scoped, except: [:new, :create]
  helper_method :sort_column, :sort_direction

  def index
    @bills = current_account.bills.uninvoiced.includes(:customer, :supplier, :category, :vat_rate).
                                              page(params[:page]).
                                              order(sort_column + " " + sort_direction)
    authorize @bills
    @bill = current_account.bills.build
    @bill.date = Date.today
    # authorize @bill
    respond_to do |format|
      format.html
      format.csv  {
        @bills = current_account.bills.includes(:customer, :supplier, :category, :vat_rate)
        send_data @bills.to_csv, filename: 'BulldogClip_bills.csv' unless @bills.empty?
      }
      format.js
    end
  end

  def new
    @bill = current_account.bills.build
    authorize @bill
    @bill.date = Date.today
    @bill.customer_id = default_customer.id if default_customer
  end

  def create
    collect_new_entries
    @bill = Bill.new(bill_params)
    authorize @bill
    if @bill.save
      # Rails.logger.debug "Supplier is #{@bill.reload.supplier_id}"
      redirect_to bills_url, notice: 'Bill was succesfully created'
    else
      render 'new'
    end
  end

  def edit
    # @bill = current_account.bill(params[:id])
    @bill = policy_scope(Bill).find(params[:id])
    authorize @bill
  end

  def update
    # @bill = current_account.bill(params[:id])
    collect_new_entries
    @bill = policy_scope(Bill).find(params[:id])
    authorize @bill
    if @bill.update(bill_params)
      flash[:success] = "Bill successfully updated"
      respond_to do |format|
        format.html {redirect_to bills_url}
        format.js {redirect_to bills_url, remote: true}
      end
    else
      render 'edit'
    end
  end

  def destroy
    @bill = current_account.bill(params[:id])
    authorize @bill
    if @bill.destroy
      flash[:success] = "Bill successfully deleted"
      redirect_to bills_url, status: 303
    else
      render 'edit'
    end
  end

  private

  def bill_params
    params.require(:bill).permit(*policy(@bill || Bill).permitted_attributes)
  end

  def collect_new_entries

    # If update then the params may be absent but the bill may still be valid.
    # If create then never valid without all three foriegn keys.
    # This method should create new entries if the id appears to be a name

    # note that this must be called before assigning params to @bills as that will
    # set invalid entries to 0 before they can be captured.


    if valid_string?(params[:bill][:supplier_id])
      new_id = Supplier.create(name: params[:bill][:supplier_id], account_id: current_account.id).id
      if new_id
        params[:bill][:supplier_id] = new_id.to_s
      else
        params[:bill][:supplier_id] = nil
      end
    end
    if valid_string?(params[:bill][:customer_id])
      new_id = Customer.create(name: params[:bill][:customer_id], account_id: current_account.id).id
      if new_id
        params[:bill][:customer_id] = new_id.to_s
      else
        params[:bill][:customer_id] = nil
      end
    end
    if valid_string?(params[:bill][:category_id])
      new_id = Category.create(name: params[:bill][:category_id], account_id: current_account.id).id
      if new_id
        params[:bill][:category_id] = new_id.to_s
      else
        params[:bill][:category_id] = nil
      end
    end
  end

  def valid_string?(str)
    # not blank, not nil and not a string representation of an integer
    # all params are strings so valid ids need converting
    str.present? && str.to_i == 0
  end

  def sort_column
    %w[date customers.name suppliers.name categories.name description amount].include?(params[:sort]) ? params[:sort] : "date"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def default_customer
    @default_customer ||= current_account.customers.is_default.first
  end
end

app/helpers/bills_helper.rb
module BillsHelper

  def get_supplier_data
    current_account.suppliers.order(:name).to_json(only: [:id, :name])
  end

  def get_customer_data
    current_account.customers.order(:name).to_json(only: [:id, :name])
  end

  def get_category_data
    current_account.categories.order(:name).to_json(only: [:id, :name])
  end

  def get_vat_rate_data
    current_account.vat_rates.active.order(:name).to_json(only: [:id, :name])
  end

  def get_header_data
    current_account.headers.order(:name) # revert to non-json format
    # current_account.headers.order(:name).to_json(only: [:id, :name])
  end

end

app/views/bills/_bill.html.erb
<tr title="click to edit" class="pointer rowlink" data-url="<%= edit_bill_path(bill)%>">
  <td class="first-col date-col"><%= bill.date %></td>
  <td class="customer-col"><%= bill.customer_name %></td>
  <td class="supplier-col"><%= bill.supplier_name %></td>
  <td class="category-col"><%= bill.category_name %></td>
  <td class="description-col-sm"><%= bill.description %></td>
  <td class="align-right amount-col"><%= number_to_currency(bill.amount) %></td>
  <% if current_account.vat_allowed? %>
    <td class="vat-rate-col"><%= bill.vat_rate_name %></td>
    <td class="align-right amount-col"><%= number_to_currency(bill.vat) %></td>
  <% end %>
</tr>

app/views/bills/_form.html.erb
<%= form_for @bill, remote: true do |f| %>
  <%= f.hidden_field :account_id %>
  <%= form_group_for f, :date, label: false do %>
    <%= f.text_field :date, class: "date_picker form-control", placeholder: "#{Date.current}"%>
  <% end %>
  <%= form_group_for f, :customer_id, label: false do %>
    <%= f.collection_select(:customer_id, current_account.customers.order(:name), :id, :name, prompt: true) %>
  <% end %>
  <%= form_group_for f, :supplier_id, label: false do %>
    <%= f.collection_select(:supplier_id, current_account.suppliers.order(:name), :id, :name, prompt: true) %>
  <% end %>
  <%= form_group_for f, :category_id, label: false do %>
    <%= f.collection_select(:category_id, current_account.categories.order(:name), :id, :name, prompt: true) %>
  <% end %>
  <%= form_group_for f, :description, label: false do %>
    <%= f.text_field :description, placeholder: 'Description', class: "form-control" %>
  <% end %>
  <%= form_group_for f, :amount, label: false do %>
    <%= f.text_field :amount, placeholder: 'Amount', class: "form-control currency", type: "tel" %>
  <% end %>
  <% if current_account.vat_allowed? %>
    <%= form_group_for f, :vat_rate_id, label: false do %>
      <%= f.collection_select(:vat_rate_id, current_account.vat_rates.active.order(:name), :id, :name, prompt: true) %>
    <% end %>
    <%= form_group_for f, :vat, label: false do %>
      <%= f.text_field :vat, placeholder: 'VAT amount', class: "form-control currency", type: "tel" %>
    <% end %>
  <% end %> <!-- end of VAT fields -->
  <%= f.submit 'Save', class: 'create-btn std-btn', title: "Save changes" %>
<% end %> <!-- end of form_for -->
  <% if action_name == 'edit' %>
    <%= button_to 'Delete', bill, method: :delete, data: {confirm: 'Are you sure?'}, class: 'warn-btn std-btn', remote: true, title: "Delete bill" %>
  <% end %>
  <%= link_to "Cancel", bills_path, class: "action-btn std-btn", remote: true, title: "Cancel and return to list of bills" %>

app/views/bills/_table.html.erb
<div class="table-responsive">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th class="first-col date-col"><%= sortable "date", "Date" %> <%= arrow "date" %></th>
        <th class="customer-col"><%= sortable "customers.name", "Customer" %> <%= arrow "customers.name" %></th>
        <th class="supplier-col"><%= sortable "suppliers.name", "Supplier" %> <%= arrow "suppliers.name" %></th>
        <th class="category-col"><%= sortable "categories.name", "Category" %> <%= arrow "categories.name" %></th>
        <th class="description-col-sm"><%= sortable "description", "Description" %> <%= arrow "description" %></th>
        <th class="amount-col"><%= sortable "amount", "Amount" %> <%= arrow "amount" %></th>
        <% if current_account.vat_allowed? %>
          <th class="vat-rate-col">VAT rate</th>
          <th class="amount-col">VAT</th>
        <% end %>
      </tr>
    </thead>
    <tbody id="bill_index_table">
        <%= render @bills %>
    </tbody>
  </table>
</div><!--end table responsive -->

app/views/bills/_video.html.erb
      <div class="table-responsive">
        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th class="first-col date-col"><%= sortable "date", "Date" %> <%= arrow "date" %></th>
              <th class="customer-col"><%= sortable "customers.name", "Customer" %> <%= arrow "customers.name" %></th>
              <th class="supplier-col"><%= sortable "suppliers.name", "Supplier" %> <%= arrow "suppliers.name" %></th>
              <th class="category-col"><%= sortable "categories.name", "Category" %> <%= arrow "categories.name" %></th>
              <th class="description-col-sm"><%= sortable "description", "Description" %> <%= arrow "description" %></th>
              <th class="amount-col"><%= sortable "amount", "Amount" %> <%= arrow "amount" %></th>
              <% if current_account.vat_allowed? %>
                <th class="vat-rate-col">VAT rate</th>
                <th class="amount-col">VAT</th>
              <% end %>
            </tr>
          </thead>
          <tbody id="bill_index_table">
          </tbody>
        </table>
      </div><!--end table responsive -->
      <div>
      <div class="panel-body" id="tutorials">
        <!-- <h2 class="video-title">VIDEO: How To Enter Your First Bill</h2> -->
        <video
          id="first_bill_video"
          class="img-responsive video-js vjs-default-skin first-video"
          title="Watch video"
          controls
          preload="auto"
          width="640"
          height="360"
          data-setup="{}"
          poster=<%= asset_path('first_bill_postit.png') %> >
          <source src= <%= video_path('First_Bill_Video.mp4') %> type='video/mp4' />
          <source src= <%= video_path('First_Bill_Video.webm') %> type='video/webm' />
          <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
        </video>
      </div>
      </div>

app/views/bills/edit.html.erb
<% content_for :title do %>BulldogClip | Edit Bill<% end %>
<% content_for :description do %>Create new bill<% end %>

<div class="container">
  <div class="col-md-4 col-md-offset-4 panel panel-default">
    <div class="panel-body">
    <h1>Edit Bill</h1>
     <a href="#" id="pop" class="info-btn pop" data-trigger="hover" data-placement="left" data-container= "body" data-original-title="How to use this page" data-content="This is how to use this page. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, quis, doloribus, dicta est culpa ipsa voluptatem incidunt eveniet molestias optio unde neque facilis cum quam ut expedita quaerat odit! Inventore, ratione, nulla atque temporibus minima cumque sapiente deleniti similique porro quam molestias nobis esse sit nisi cupiditate iure dolorum laborum."><img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/></a>
      <%= render partial: 'form', locals: {bill: @bill} %>
    </div>
  </div>
</div>

app/views/bills/edit.js.erb
$('#modal_title').html('Edit Bill');
$('#bill_form').html('<%= escape_javascript render partial: 'form', locals: {bill: @bill} %>');
$('#bill_modal').on('show.bs.modal', UTIL.init);
$('#bill_modal').modal('show');

app/views/bills/index.html.erb
<% content_for :title do %>BulldogClip | Bills<% end %>
<% content_for :description do %>BulldogClip bills index<% end %>

<div class="container">

  <h1>Bills</h1>

     <a href="#" id="pop" class="info-btn pop"
     data-title="Bills Index"
     data-content="
     <ul class='info-ul'>
     <li>All of your bills which have not been added to an invoice are listed here.</li>
     <li>Use 'New' to enter a new bill.</li>
     <li>You can edit or delete a bill by selecting the row in the table.</li>
     <li>'Export' downloads the table as a CSV file.</li>
     <li>Click on column headings to sort the data table.</li>
     <li>Go to the Analysis page if you want to find specific bills that have already been added to a document.</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

     <!-- data-trigger="hover" data-placement="left" data-container= "body" -->

  <div class="panel panel-default">
    <div class="panel-body">

      <%= link_to "New", new_bill_path, remote: true, class: "create-btn std-btn", data: {toggle: "tooltip"}, title: "Create a new bill" %>
      <%= link_to "Export", bills_path(format: "csv"), class: "action-btn std-btn", data: {toggle: "tooltip"}, title: "Download a CSV file of your bills"  %>

<!-- Displays first bill video if no bills or bill table -->
      <% if current_account.bills.empty? %>
        <%= render 'video' %>
      <% else %>
        <%= render 'table' %>
      <% end %>

      <div id="paginator">
        <%= paginate @bills, remote: true %>
      </div>
    </div><!--end panel body -->
  </div><!--end panel -->

</div><!--end container -->

  <!-- Modal -->
  <div class="modal fade" id="bill_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="modal_title">New Bill</h4>
        </div>
        <div class="modal-body" id="bill_form">
          <%#= render 'form' %>
          loading ...
        </div>
        <div class="modal-footer">
<!--=<button type="button" class="action-btn std-btn" data-dismiss="modal">Cancel</button>
          <button type="button" class="create-btn std-btn">Submit</button> -->
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/bills/index.js.erb
$('#flashes').remove();
$('main').prepend("<%= escape_javascript raw(flash_normal) %>");
$('tbody#bill_index_table').html('<%= escape_javascript render @bills %>');
$('#paginator').html('<%= escape_javascript(paginate(@bills, :remote => true).to_s) %>');
$('#bill_modal').modal('hide');

app/views/bills/new.html.erb
<% content_for :title do %>BulldogClip | New Bill<% end %>
<% content_for :description do %>Create new bill<% end %>

<div class="container">
  <div class="col-md-4 col-md-offset-4 panel panel-default">
    <div class="panel-body">
    <h1>New Bill</h1>
     <a href="#" id="pop" class="info-btn pop" data-trigger="hover" data-placement="left" data-container= "body" data-original-title="How to add a new bill" data-content="Complete the form using the drop down menus and text fields."><img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/></a>
      <%= render partial: 'form', locals: {bill: @bill} %>
    </div>
  </div>
</div>

app/views/bills/new.js.erb
$('#modal_title').html('New Bill');
$('#bill_form').html('<%= escape_javascript render partial: 'form', locals: {bill: @bill} %>');
$('#bill_modal').on('show.bs.modal', UTIL.init);
$('#bill_modal').modal('show');