config/routes.rb
Bulldog::Application.routes.draw do

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
      get '/edit_email' => 'registrations#edit_email', :via => :get, :as => :edit_email_user_registration
  end
  devise_for :users, path: "", controllers: {confirmations: 'confirmations',
                                              sessions: 'sessions',
                                              registrations: 'registrations'}

  # get '/remote_sign_in' => 'remote_content#remote_sign_in', as: :remote_sign_in

  resources :accounts do
    member do
      get 'cancel'
      get 'new_card'
      patch 'update_card'
    end
  end
  resources :bills, except: :show
  resources :customers, except: :show
  resources :invoices
  resources :reports, only: [:new, :create]
  get 'reports' => 'reports#new'
  resources :categories
  resources :vat_rates
  resources :settings, only: [:index, :show, :edit, :update]
  resources :suppliers, only: [:index, :edit, :update]
  resources :welcome, only: [:index]
  resources :plans, only: [:index]
  # post '/send_mail' => 'contacts#send_mail'
  resources :contacts, only: [:new, :create]
  # get "help/:action" => "help#:action"
  get 'help/intro' => 'help#intro'
  get 'help/account' => 'help#account'
  get 'help/bills' => 'help#bills'
  get 'help/categories' => 'help#categories'
  get 'help/customers' => 'help#customers'
  get 'help/invoices' => 'help#invoices'
  get 'help/logo' => 'help#logo'
  get 'help/print_settings' => 'help#print_settings'
  get 'help/reports' => 'help#reports'
  get 'help/setup' => 'help#setup'
  get 'help/subscription' => 'help#subscription'
  get 'help/suppliers' => 'help#suppliers'
  get 'help/vat' => 'help#vat'
  get 'help/video' => 'help#video'

end

app/models/account.rb
class Account < ActiveRecord::Base

  include AASM

  belongs_to :user
  has_many :suppliers
  has_many :customers
  has_many :categories
  has_many :bills
  has_many :invoices
  has_many :vat_rates
  has_many :headers
  has_many :sales
  has_one  :setting
  belongs_to :plan

  after_create  :create_setting

  validates :name, :email, :plan_id, presence: true
  validates :email, uniqueness: true, format: {with: /\A[^@]+@[^@]+\z/}, on: :create

  # scope :owned_by_user, -> { where(user_id: current_user.id) }
  attr_accessor :stripe_card_token, :mail_list

  # Stripe Plans: 1: Personal annual, 2: Business monthly, 3: Business annual

  PLANS = { 1 => :personal, 2 => :business, 3 => :business }

  aasm column: 'state' do
    state :pending, initial: true
    state :trialing
    state :paying  # when card added and previous state expired
    state :paid    # when charge succeeds
    state :expired # when trial ended
    state :charge_failed
    state :closed  # when account cancelled
    state :deleted

    event :sign_up do # account create event
      transitions from: :pending, to: :trialing
    end

    event :add_card do # account update card event
      transitions from: :expired, to: :paying
      transitions from: :trialing, to: :trialing
      transitions from: :paid, to: :paid
      transitions from: :paying, to: :paying
      transitions from: :charge_failed, to: :charge_failed
    end

    event :charge do  # webhook event
      transitions from: :paying, to: :paid
      transitions from: :trialing, to: :paid
      transitions from: :paid, to: :paid
      transitions from: :charge_failed, to: :paid
    end

    event :expire do  # welcome_controller sign_in event
      transitions from: :trialing, to: :expired
    end

    event :charge_failed do # webhook event
      transitions from: :paid, to: :charge_failed  # webhook event - failed charge
      transitions from: :paying, to: :charge_failed  # webhook event - failed charge
      transitions from: :trialing, to: :charge_failed  # webhook event - failed charge
    end

    event :close do   # account cancellation event
      transitions from: :paid, to: :closed
      transitions from: :trialing, to: :closed
    end

    event :restart do # option offered when login after cancelled account
      transitions from: :closed, to: :paying  # change plan event
    end

    event :delete do
      transitions from: :closed, to: :deleted
    end
  end

  def subscription_type
    PLANS[plan_id]
  end

  def business?
    subscription_type == :business
  end

  def personal?
    subscription_type == :personal
  end

  def active?
    # plan_id.present? && plan_id > 0
    trialing? || paid? || paying?
  end

  def self.owned_by_user(user)
    where(user_id: user.id)
  end

  def owner
    user
  end

  def customer(id)
    customers.find(id)
  end

  def supplier(id)
    suppliers.find(id)
  end

  def category(id)
    categories.find(id)
  end

  def bill(id)
    bills.find(id)
  end

  def invoice(id)
    invoices.find(id)
  end

  def vat_allowed?
    vat_enabled? && business?
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  after_action :verify_authorized

  def show
    @account = Account.owned_by_user(current_user).find(params[:id])
    authorize @account
  end

  def new
    plan = Plan.find(params[:plan_id])
    @account = plan.accounts.build
    authorize @account
    @title = params[:title]
    @price = params[:price]
    @interval = params[:interval]
  end

  def new_card
    @account = policy_scope(Account).find(params[:id])
    authorize @account
  end

  def update_card
    @account = policy_scope(Account).find(params[:id])
    authorize @account
    call_update_card_service(@account)
    if @account.errors.empty?
      if @account.active?
        flash[:success] = "Thankyou. Your card details have been updated"
        redirect_to @account
      else
        flash[:success] = "Thankyou. Your card details have been updated"
        sign_out current_user
        redirect_to page_path('waiting_payment')
      end
    else
      flash[:error] = "There was a problem with your payment card"
      render :new_card
    end
  end

  def edit
    @account = Account.owned_by_user(current_user).find(params[:id])
    authorize @account
  end

  def update
    @account = Account.find(params[:id])
    authorize @account
    @account.assign_attributes(account_params)
    UpdateAccount.call(@account)
    if @account.errors.empty?
      if @account.closed?
        sign_out current_user
        redirect_to page_path('goodbye')
      else
        redirect_to @account, notice: "Account successfully updated"
      end
    else
      if is_cancellation?
        flash[:error] = "There was a problem with this transaction"
        render 'show'
      else
        flash[:error] = "There was a problem with this transaction"
        render 'edit'
      end
    end
  end

  def create
    @account = Account.new(account_params)
    authorize @account
    @account = CreateAccount.call(account_params)
    if @account.persisted?
      redirect_to page_path('new_account')
    else
      flash[:error] = @account.errors.full_messages
      render 'new'
    end
  end

  def cancel
    @account = Account.owned_by_user(current_user).find(params[:id])
    authorize @account
  end

  private

  def call_update_card_service(account)
    account = UpdateCard.call({
      account: account,
      token: params[:account][:stripe_card_token]
      })
    # account.add_card! if account.errors.empty?
    # account
    Rails.logger.info "account errors: #{account.errors.full_messages}"
    account
  end

  def account_params
    params.require(:account).permit(*policy(@account || Account).permitted_attributes)
  end

  def record_not_found
    flash[:error] = "You don't have access to that account"
    # begin
      # redirect_to :back
      redirect_back(fallback_location: root_path)
    # rescue ActionController::RedirectBackError
    #   redirect_to root_path
    # end
  end

  def is_cancellation?
    params[:account][:plan_id] == "0"
  end
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>

  <%= form_group_for f, :name, label: false do %>
    <div class="input-group name">
      <%= f.label :name, "Account name", class: 'acct_name' %>
      <%= f.text_field :name, autofocus: true, class: 'form-control acct_name', placeholder: 'Enter account name' %>
    </div>
  <% end %>

  <%= form_group_for f, :plan_id do %>
    <%= f.hidden_field :plan_id, data: {plans: get_plan_data} %>
  <% end %>

  <% if @account.business? %>
    <%= form_group_for f, :vat_enabled, label: false do %>
      <div class="input-group vat-check">
        <%= f.label "Enable VAT on bills?" %>
        <%= f.check_box :vat_enabled, id: 'check_vat' %>
      </div>
    <% end %>
  <% end %>

  <%= f.submit 'Save', :class => 'create-btn std-btn', data: {toggle: "tooltip"}, title: "Save account settings"  %>
  <%= link_to 'Cancel', account_path(@account), class: 'action-btn std-btn', data: {toggle: "tooltip"}, title: "Cancel and return to account details"  %>

<% end %>

app/views/accounts/cancel.html.erb
<% content_for :title do %>BulldogClip | Cancel Subscription<% end %>
<% content_for :description do %>Cancel subscription<% end %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 panel panel-default">
    <div class="panel-body">
      <h1>Subscription Cancellation</h1>

     <a href="#" id="pop" class="info-btn pop"
     data-title="Cancel subscription"
     data-content="
     <ul class='info-ul'>
     <li>Cancelling your subscription will disable your account.</li>
     <li>Please ensure that you have a copy of your data before you go.</li>
     <li>Use the 'Back' button to keep the account active.</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

      <table class="account-details">
        <tr>
          <td class="td-name">Name</td><td class="td-content"><%= @account.name %></td>
        </tr>

        <tr>
          <td class="td-name">Current Plan</td>
          <td class="td-content"><%= current_plan_name(@account) %></td>
        </tr>

        <tr>
          <td class="td-name">Paid up until</td>
          <td class="td-content"><%= next_invoice_date(@account) %><%= time_to_next_invoice(@account) %></td>
        </tr>

      </table>
      <br/>

      <%= link_to 'Back', account_path(@account), class: "action-btn std-btn", data: {toggle: "tooltip"}, title: "Back to account details"  %>
      <%= link_to 'Cancel subscription', account_path(@account, account: {plan_id: 0}), method: :patch, class: "warn-btn std-btn", data: {confirm: "Are you sure?"}, title: "Cancel subscription"  %>
    </div>
  </div>
</div>

app/views/accounts/edit.html.erb
<% content_for :title do %>BulldogClip | Edit Account<% end %>
<% content_for :description do %>Reset BulldogClip password<% end %>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 panel panel-default">
    <div class="panel-body">
      <div class = 'authform'>
        <h1>Account Details</h1>

     <a href="#" id="pop" class="info-btn pop"
     data-title="Edit Your Account Details"
     data-content="
     <ul class='info-ul'>
     <li>You can edit the account name. We may use it in the future to improve the friendliness of our communications with you. It doesn't appear on any documents (yet).</li>
     <li>If you choose to change plans to one with a different payment interval or
     amount, we will prorate any difference at your next billing date.</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<% content_for :title do %>BulldogClip | New Account<% end %>
<% content_for :description do %>Create new account<% end %>

<div class="container stripe">
  <div class="col-md-4 col-md-offset-4 panel panel-default stripe">
    <div class="stripe-header">
      <h1 class="secure"><%= @title %></h1>
    </div>
    <hr>
    <%= form_for @account do |f| %>
    <div class="panel-body sensitive well">
      <%= f.hidden_field :plan_id %>
      <%= form_group_for f, :name, label: false do %>
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Your name' %>
      <% end %>
      <%= form_group_for f, :email, label: false do %>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', placeholder: 'Verification email sent here' %>
      <% end %>

      <div class="checkbox contact-us">
        <%= f.check_box :mail_list, checked: 'checked' %>
        <%= f.label :mail_list, 'Please add me to the mailing list' %>
      </div>
    </div><!-- end sensitive well -->
    <div class="col-xs-5 price">
      <div class="row">
        <p class="interval">30 days full access</p>
        <h3 class="price">FREE</h3>
<!--         <p class="interval">then <%= @price %> <%= @interval %></p>
 -->      </div>
    </div>
    <div class="col-xs-7 subscribe">
    <%= f.submit "Start Free Trial", class: "create-btn std-btn lg-btn pay pull-right", data: {toggle: "tooltip"}, title: "Subscribe to BulldogClip", id: "ga_subscribe" %>
    </div>
    <% end %><!-- end of the form -->
  </div><!-- end panel-default -->
</div><!-- end container -->

app/views/accounts/new_card.html.erb
<% content_for :title do %>BulldogClip | New Card<% end %>
<% content_for :description do %>Update card for account<% end %>

<div class="container stripe">
  <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 panel panel-default stripe">
    <div class="stripe-header">
      <h1 class="secure">New Card Details</h1>
    </div>
    <hr>
    <div class="stripe-secure">
      <img src=<%= asset_path('padlock.png') %> alt="padlock" class="secure img-responsive">
      <p class="secure">SSL encrypted secure</p>
      <img src=<%= asset_path('stripe.png') %> alt="powered by stripe" class="stripe-power pull-right">
    </div>
    <%= form_for @account, url: update_card_account_path do |f| %>
    <div class="panel-body sensitive well">
      <%= f.hidden_field :stripe_card_token %>

      <div class="field card-number">
        <%= label_tag :card_number, "Card Number" %>
        <%= text_field_tag :card_number, nil, name: nil, class: "form-control card-number", placeholder: "16 digit card number", type: "tel", required: 'required' %>
        <img src=<%= asset_path('cc.png') %> alt="card types accepted" class="cards">
      </div>
      <!-- <div class="field"> -->
      <!-- </div> -->
      <div class="row">
        <div class="col-xs-4 cvc-exp">
          <div class="field card-expiration" >
            <%= label_tag :cc_exp, "Expiry Date" %>
            <input id="cc_exp" type="tel" class="form-control expiry-date" placeholder="MM / YY" autocompletetype="cc-exp" required="required">
          </div>
        </div>
        <div class="col-xs-8 cvc-exp">
          <div class="field cvc">
            <%= label_tag :card_code, "Security Code (CVC)", class: "cvc" %>
            <%= text_field_tag :card_code, nil, name: nil, class: "form-control cvc", placeholder: "123", type: "tel", required: 'required' %>
            <img src=<%= asset_path('cvc.png') %> alt="CVC on back of card" class="cvc">
          </div>
        </div>
      </div>
    </div><!-- end sensitive well -->
    <div id="stripe_error" class="stripe-error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>

    <div class="col-xs-12 subscribe">
    <%= f.submit "Update Card", class: "create-btn std-btn lg-btn pull-right update-card", data: {toggle: "tooltip"}, title: "Update payment card for BulldogClip subscription" %>
    <!-- </div> -->
    <%= link_to 'Cancel', account_path(@account), class: "action-btn std-btn lg-btn pull-right",
      data: {toggle: "tooltip"}, title: "Cancel changes" %>
    <% end %><!-- end of the form -->
  </div><!-- end panel-default -->
</div><!-- end container -->

app/views/accounts/show.html.erb
<% content_for :title do %>BulldogClip | Account<% end %>
<% content_for :description do %>User account details<% end %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 panel panel-default">
    <div class="panel-body">
      <h1>Subscription Details</h1>

     <a href="#" id="pop" class="info-btn pop"
     data-title="Your Subscription Details"
     data-content="
     <ul class='info-ul'>
     <li>See also 'Tools - Document Setup' for document specific account settings</li>
     <!-- <li>'Change Plan' allows you to upgrade your plan or enable VAT (business plan only).</li> -->
     <!-- <li>Use the 'Update Card' button to change your payment card or reset its expiry date.</li> -->
     <li>We hope that you do not wish to 'Cancel Subscription' but this is where you can start the process.</li>
     </ul>">
     <img src=<%= asset_path('info_btn.png') %> alt="info button" class="info-img"/>
     </a>

      <table class="account-details">
        <tr>
          <td class="td-name">Name</td><td class="td-content"><%= @account.name %></td>
        </tr>

        <tr>
          <td class="td-name">Current Plan</td>
          <td class="td-content"><%= current_plan_name(@account) %></td>
        </tr>

        <tr>
          <td class="td-name">Next payment due</td>
          <td class="td-content"><%= next_invoice_date(@account) %></td>
        </tr>

        <tr>
          <td class="td-name">Card ending</td>
          <td class="td-content"><%= current_card(@account) %></td>
        </tr>

        <% if @account.business? %>
          <tr>
            <td class="td-name">Enable VAT on bills?</td>
            <td class="td-content"><%= @account.vat_enabled? ? "Yes" : "No" %></td>
          </tr>
        <% end %>

      </table>
      <br/>

      <%#= link_to 'Edit', edit_account_path(@account), class: "create-btn std-btn", data: {toggle: "tooltip"}, title: "Edit account settings"  %>
      <%#= link_to 'Change Plan', edit_account_path(@account), class: "create-btn std-btn", data: {toggle: "tooltip"}, title: "Change subscription plan or options"  %>
      <%#= link_to 'Update card', new_card_account_path(@account), class: "action-btn std-btn", data: {toggle: "tooltip"}, title: "Change payment card details"  %>
      <%#= link_to 'Billing history', edit_account_path(@account), class: "action-btn std-btn", data: {toggle: "tooltip"}, title: "View billing history" %>
      <%= link_to 'Cancel subscription', cancel_account_path(@account), class: "warn-btn std-btn", data: {toggle: "tooltip"}, title: "Cancel Subscription"  %>
      <%#= link_to 'Change Password', edit_user_registration_path, class: "warn-btn std-btn" %>
    </div>
  </div>
</div>